name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  OPENWEATHERMAP_KEY: ${{ secrets.OPENWEATHERMAP_KEY }}
  WEATHERAPICOM_KEY: ${{ secrets.WEATHERAPICOM_KEY }}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build -j $(nproc)
    - name: Run tests
      run: env OPENWEATHERMAP_KEY=${{ secrets.OPENWEATHERMAP_KEY }} WEATHERAPICOM_KEY=${{ secrets.WEATHERAPICOM_KEY }} cargo test --verbose
